######################################################################
# Automatically generated by qmake (2.01a) ?? 2? 29 15:27:37 2020
######################################################################

TEMPLATE = app
TARGET = test
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += \
	main.cpp \
	mainwindow.cpp

HEADERS += mainwindow.h

FORMS += mainwindow.ui

QT += gui core widgets

