######################################################################
# Automatically generated by qmake (2.01a) ?? 2? 29 23:29:53 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MyDialog.h model.h
FORMS += MyDialog.ui
SOURCES += main.cpp MyDialog.cpp model.cpp


QT += widgets
