######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 12 00:34:57 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += addStuDlg.h
FORMS += addStuDlg.ui
SOURCES += addStuDlg.cpp main.cpp

QMAKE_CXXFLAGS += -g -O0
