######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 12 00:34:57 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += addStuDlg.h StuMgmtMainWindow.h QueryStuDlg.h
FORMS += addStuDlg.ui StuMgmtMainWindow.ui QueryStuDlg.ui
SOURCES += addStuDlg.cpp StuMgmtMainWindow.cpp main.cpp QueryStuDlg.cpp

QMAKE_CXXFLAGS += -g -O0
